-- Supabase schema for the news monitoring database.
-- Run this once in Supabase SQL Editor before enabling GitHub Actions secrets.

create table if not exists public.report_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  report_date date not null,
  report_slot text not null,
  timestamp timestamptz,
  window_label text,
  window_start timestamptz,
  window_end timestamptz,
  risk_level text default 'LOW',
  metrics jsonb default '{}'::jsonb,
  briefing text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_articles (
  id bigint generated by default as identity primary key,
  article_hash text not null unique,
  report_date date not null,
  report_slot text,
  window_label text,
  window_start timestamptz,
  window_end timestamptz,
  risk_level text default 'LOW',
  title text not null,
  link text,
  source text,
  keyword text,
  pub_date timestamptz,
  pub_date_raw text,
  score integer default 0,
  category text default 'other',
  tone text default 'neutral',
  cluster_size integer default 1,
  status text not null default 'new',
  owner text,
  memo text,
  raw jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.monitor_keywords (
  keyword text primary key,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_news_articles_report_date on public.news_articles (report_date desc);
create index if not exists idx_news_articles_category on public.news_articles (category);
create index if not exists idx_news_articles_tone on public.news_articles (tone);
create index if not exists idx_news_articles_status on public.news_articles (status);
create index if not exists idx_news_articles_keyword on public.news_articles (keyword);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_report_runs_updated_at on public.report_runs;
create trigger set_report_runs_updated_at
before update on public.report_runs
for each row execute function public.set_updated_at();

drop trigger if exists set_news_articles_updated_at on public.news_articles;
create trigger set_news_articles_updated_at
before update on public.news_articles
for each row execute function public.set_updated_at();

drop trigger if exists set_monitor_keywords_updated_at on public.monitor_keywords;
create trigger set_monitor_keywords_updated_at
before update on public.monitor_keywords
for each row execute function public.set_updated_at();

alter table public.report_runs enable row level security;
alter table public.news_articles enable row level security;
alter table public.monitor_keywords enable row level security;

-- Service role writes from GitHub Actions bypass RLS.
-- Public dashboard read access.
-- The anon key can only SELECT the columns explicitly granted below.
-- Inserts/updates still require the service role used by GitHub Actions.
revoke all on public.news_articles from anon;
grant select (
  article_hash,
  report_date,
  report_slot,
  window_label,
  risk_level,
  title,
  link,
  source,
  keyword,
  pub_date,
  pub_date_raw,
  score,
  category,
  tone,
  cluster_size,
  status
) on public.news_articles to anon;

drop policy if exists "public dashboard read news articles" on public.news_articles;
create policy "public dashboard read news articles"
on public.news_articles
for select
to anon
using (true);

revoke all on public.report_runs from anon;
drop policy if exists "public dashboard read report runs" on public.report_runs;

grant select, insert, update, delete on public.monitor_keywords to anon;

drop policy if exists "public dashboard manage monitor keywords" on public.monitor_keywords;
create policy "public dashboard manage monitor keywords"
on public.monitor_keywords
for all
to anon
using (true)
with check (true);

insert into public.monitor_keywords (keyword, enabled)
values
  ('인카금융', true),
  ('인카금융서비스', true),
  ('보험 마케팅', true),
  ('생명보험', true),
  ('손해보험', true),
  ('보험 프로모션', true),
  ('GA 보험', true),
  ('보험설계사', true),
  ('보험대리점 브랜드평판', true),
  ('GA 브랜드평판', true),
  ('인카금융서비스 브랜드평판', true)
on conflict (keyword) do nothing;
