-- Supabase schema for the news monitoring database.
-- Run this once in Supabase SQL Editor before enabling GitHub Actions secrets.

create table if not exists public.report_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  report_date date not null,
  report_slot text not null,
  timestamp timestamptz,
  window_label text,
  window_start timestamptz,
  window_end timestamptz,
  risk_level text default 'LOW',
  metrics jsonb default '{}'::jsonb,
  briefing text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_articles (
  id bigint generated by default as identity primary key,
  article_hash text not null unique,
  report_date date not null,
  report_slot text,
  window_label text,
  window_start timestamptz,
  window_end timestamptz,
  risk_level text default 'LOW',
  title text not null,
  link text,
  source text,
  keyword text,
  summary text,
  pub_date timestamptz,
  pub_date_raw text,
  score integer default 0,
  category text default 'other',
  tone text default 'neutral',
  cluster_size integer default 1,
  status text not null default 'new',
  owner text,
  memo text,
  raw jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.monitor_keywords (
  keyword text,
  category text not null default 'other',
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (keyword, category)
);

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'monitor_keywords_category_check'
       and conrelid = 'public.monitor_keywords'::regclass
  ) then
    alter table public.monitor_keywords
      add constraint monitor_keywords_category_check
      check (category in ('own', 'regulation', 'competitor', 'industry', 'other', 'exclude'));
  end if;
end $$;

create table if not exists public.media_relations (
  name text primary key,
  status text default '중립',
  grade text default 'B',
  owner text,
  contact_date date,
  memo text,
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reporters (
  id bigint generated by default as identity primary key,
  name text not null,
  media text not null,
  status text default '중립',
  contact_date date,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ad_spends (
  id bigint generated by default as identity primary key,
  media text not null,
  spend_month text not null,
  amount numeric not null default 0,
  spend_type text default '광고',
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.press_aliases (
  host text primary key,
  press_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.article_scraps (
  article_hash text primary key,
  article_snapshot jsonb not null default '{}'::jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_sends (
  id bigint generated by default as identity primary key,
  sent_at timestamptz not null default now(),
  channel text not null default 'kakao',
  message_type text not null,
  dedupe_key text,
  title text,
  body text,
  link_url text,
  status text not null default 'success',
  error text,
  provider_response jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.negative_watch_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  scanned_at timestamptz not null default now(),
  minutes_back integer not null default 5,
  scanned_count integer not null default 0,
  negative_count integer not null default 0,
  new_negative_count integer not null default 0,
  status text not null default 'scanned',
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.job_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  job_type text not null,
  report_date date,
  report_slot text,
  expected_at timestamptz,
  triggered_by text,
  provider text,
  workflow text,
  github_run_id text,
  github_run_attempt text,
  status text not null default 'started',
  started_at timestamptz,
  finished_at timestamptz,
  last_seen_at timestamptz not null default now(),
  dispatch_count integer not null default 0,
  error text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.classification_feedback (
  id bigint generated by default as identity primary key,
  article_hash text,
  title text,
  link text,
  previous_category text,
  previous_tone text,
  corrected_category text,
  corrected_tone text,
  reason text,
  created_by text,
  created_at timestamptz not null default now()
);

alter table public.news_articles add column if not exists summary text;
update public.news_articles
set summary = coalesce(nullif(summary, ''), raw->>'description', raw->>'summary')
where summary is null or summary = '';

create index if not exists idx_news_articles_report_date on public.news_articles (report_date desc);
create index if not exists idx_news_articles_category on public.news_articles (category);
create index if not exists idx_news_articles_tone on public.news_articles (tone);
create index if not exists idx_news_articles_status on public.news_articles (status);
create index if not exists idx_news_articles_keyword on public.news_articles (keyword);
create index if not exists idx_report_runs_report_date on public.report_runs (report_date desc);
create index if not exists idx_monitor_keywords_category on public.monitor_keywords (category, created_at);
create index if not exists idx_media_relations_hidden on public.media_relations (hidden);
create index if not exists idx_reporters_media on public.reporters (media);
create index if not exists idx_ad_spends_month on public.ad_spends (spend_month);
create index if not exists idx_notification_sends_sent_at on public.notification_sends (sent_at desc);
create unique index if not exists idx_notification_sends_dedupe_key on public.notification_sends (dedupe_key);
create index if not exists idx_notification_sends_type_title_status on public.notification_sends (message_type, title, status);
create index if not exists idx_negative_watch_runs_scanned_at on public.negative_watch_runs (scanned_at desc);
create index if not exists idx_job_runs_expected_at on public.job_runs (expected_at desc);
create index if not exists idx_job_runs_type_status on public.job_runs (job_type, status, last_seen_at desc);
create index if not exists idx_job_runs_report_slot on public.job_runs (report_date desc, report_slot);
create index if not exists idx_classification_feedback_article on public.classification_feedback (article_hash);
create index if not exists idx_classification_feedback_created_at on public.classification_feedback (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_report_runs_updated_at on public.report_runs;
create trigger set_report_runs_updated_at
before update on public.report_runs
for each row execute function public.set_updated_at();

drop trigger if exists set_news_articles_updated_at on public.news_articles;
create trigger set_news_articles_updated_at
before update on public.news_articles
for each row execute function public.set_updated_at();

drop trigger if exists set_monitor_keywords_updated_at on public.monitor_keywords;
create trigger set_monitor_keywords_updated_at
before update on public.monitor_keywords
for each row execute function public.set_updated_at();

drop trigger if exists set_media_relations_updated_at on public.media_relations;
create trigger set_media_relations_updated_at
before update on public.media_relations
for each row execute function public.set_updated_at();

drop trigger if exists set_reporters_updated_at on public.reporters;
create trigger set_reporters_updated_at
before update on public.reporters
for each row execute function public.set_updated_at();

drop trigger if exists set_ad_spends_updated_at on public.ad_spends;
create trigger set_ad_spends_updated_at
before update on public.ad_spends
for each row execute function public.set_updated_at();

drop trigger if exists set_press_aliases_updated_at on public.press_aliases;
create trigger set_press_aliases_updated_at
before update on public.press_aliases
for each row execute function public.set_updated_at();

drop trigger if exists set_article_scraps_updated_at on public.article_scraps;
create trigger set_article_scraps_updated_at
before update on public.article_scraps
for each row execute function public.set_updated_at();

drop trigger if exists set_job_runs_updated_at on public.job_runs;
create trigger set_job_runs_updated_at
before update on public.job_runs
for each row execute function public.set_updated_at();

alter table public.classification_feedback enable row level security;

alter table public.report_runs enable row level security;
alter table public.news_articles enable row level security;
alter table public.monitor_keywords enable row level security;
alter table public.media_relations enable row level security;
alter table public.reporters enable row level security;
alter table public.ad_spends enable row level security;
alter table public.press_aliases enable row level security;
alter table public.article_scraps enable row level security;
alter table public.notification_sends enable row level security;
alter table public.negative_watch_runs enable row level security;
alter table public.job_runs enable row level security;

-- Service role writes from GitHub Actions bypass RLS.
-- Public dashboard read access is intentionally narrow.
-- Writes and privileged reads must go through Edge Functions with a verified dashboard session.
revoke all on public.news_articles from anon;
grant select (
  article_hash,
  report_date,
  report_slot,
  window_label,
  risk_level,
  title,
  link,
  source,
  keyword,
  summary,
  pub_date,
  pub_date_raw,
  score,
  category,
  tone,
  cluster_size,
  status
) on public.news_articles to anon;

drop policy if exists "public dashboard read news articles" on public.news_articles;
create policy "public dashboard read news articles"
on public.news_articles
for select
to anon
using (true);

drop policy if exists "public dashboard write news articles" on public.news_articles;

revoke all on public.report_runs from anon;
grant select on public.report_runs to anon;
drop policy if exists "public dashboard read report runs" on public.report_runs;
drop policy if exists "public dashboard manage report runs" on public.report_runs;
create policy "public dashboard read report runs"
on public.report_runs
for select
to anon
using (true);

grant select on public.monitor_keywords to anon;

drop policy if exists "public dashboard manage monitor keywords" on public.monitor_keywords;
create policy "public dashboard read monitor keywords"
on public.monitor_keywords
for select
to anon
using (true);

revoke all on public.media_relations from anon, authenticated;
revoke all on public.reporters from anon, authenticated;
revoke all on public.ad_spends from anon, authenticated;
revoke all on public.press_aliases from anon, authenticated;
revoke all on public.article_scraps from anon, authenticated;
revoke all on public.notification_sends from anon, authenticated;
revoke all on public.negative_watch_runs from anon, authenticated;
revoke all on public.job_runs from anon, authenticated;
revoke all on public.classification_feedback from anon, authenticated;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "public dashboard manage media relations" on public.media_relations;

drop policy if exists "public dashboard manage reporters" on public.reporters;

drop policy if exists "public dashboard manage ad spends" on public.ad_spends;

drop policy if exists "public dashboard manage press aliases" on public.press_aliases;

insert into public.monitor_keywords (keyword, category, enabled)
values
  ('인카금융', 'own', true),
  ('인카금융서비스', 'own', true),
  ('보험 마케팅', 'industry', true),
  ('생명보험', 'competitor', true),
  ('손해보험', 'competitor', true),
  ('보험 프로모션', 'industry', true),
  ('GA 보험', 'industry', true),
  ('보험설계사', 'industry', true),
  ('보험대리점 브랜드평판', 'industry', true),
  ('GA 브랜드평판', 'industry', true),
  ('인카금융서비스 브랜드평판', 'own', true)
on conflict (keyword, category) do nothing;
