-- Supabase schema for the news monitoring database.
-- Run this once in Supabase SQL Editor before enabling GitHub Actions secrets.

create table if not exists public.report_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  report_date date not null,
  report_slot text not null,
  timestamp timestamptz,
  window_label text,
  window_start timestamptz,
  window_end timestamptz,
  risk_level text default 'LOW',
  metrics jsonb default '{}'::jsonb,
  briefing text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_articles (
  id bigint generated by default as identity primary key,
  article_hash text not null unique,
  report_date date not null,
  report_slot text,
  window_label text,
  window_start timestamptz,
  window_end timestamptz,
  risk_level text default 'LOW',
  title text not null,
  link text,
  source text,
  keyword text,
  pub_date timestamptz,
  pub_date_raw text,
  score integer default 0,
  category text default 'other',
  tone text default 'neutral',
  cluster_size integer default 1,
  status text not null default 'new',
  owner text,
  memo text,
  raw jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_news_articles_report_date on public.news_articles (report_date desc);
create index if not exists idx_news_articles_category on public.news_articles (category);
create index if not exists idx_news_articles_tone on public.news_articles (tone);
create index if not exists idx_news_articles_status on public.news_articles (status);
create index if not exists idx_news_articles_keyword on public.news_articles (keyword);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_report_runs_updated_at on public.report_runs;
create trigger set_report_runs_updated_at
before update on public.report_runs
for each row execute function public.set_updated_at();

drop trigger if exists set_news_articles_updated_at on public.news_articles;
create trigger set_news_articles_updated_at
before update on public.news_articles
for each row execute function public.set_updated_at();

alter table public.report_runs enable row level security;
alter table public.news_articles enable row level security;

-- Service role writes from GitHub Actions bypass RLS.
-- Keep browser access closed for now. The GitHub Pages dashboard is generated
-- as static JSON by GitHub Actions, so Supabase does not need public policies yet.
-- Add authenticated select/update policies later for an internal editing screen.
