create table if not exists public.classification_feedback (
  id bigint generated by default as identity primary key,
  article_hash text,
  title text,
  link text,
  previous_category text,
  previous_tone text,
  corrected_category text,
  corrected_tone text,
  reason text,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_classification_feedback_article
  on public.classification_feedback (article_hash);

create index if not exists idx_classification_feedback_created_at
  on public.classification_feedback (created_at desc);

alter table public.classification_feedback enable row level security;
revoke all on public.classification_feedback from anon, authenticated;

-- Refresh requests and AI-generation actions should be routed through Edge
-- Functions that verify dashboard sessions. Keep the raw feedback table private
-- until that write path is added.

revoke insert, update, delete on public.news_articles from anon, authenticated;
revoke insert, update, delete on public.report_runs from anon, authenticated;
revoke insert, update, delete on public.monitor_keywords from anon, authenticated;
revoke all on public.media_relations from anon, authenticated;
revoke all on public.reporters from anon, authenticated;
revoke all on public.ad_spends from anon, authenticated;
revoke all on public.press_aliases from anon, authenticated;

drop policy if exists "public dashboard write news articles" on public.news_articles;
drop policy if exists "public dashboard manage report runs" on public.report_runs;
drop policy if exists "public dashboard manage monitor keywords" on public.monitor_keywords;
drop policy if exists "public dashboard manage media relations" on public.media_relations;
drop policy if exists "public dashboard manage reporters" on public.reporters;
drop policy if exists "public dashboard manage ad spends" on public.ad_spends;
drop policy if exists "public dashboard manage press aliases" on public.press_aliases;
