create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public;

alter table public.dashboard_users add column if not exists role text not null default 'viewer';
alter table public.dashboard_users add column if not exists failed_login_count integer not null default 0;
alter table public.dashboard_users add column if not exists locked_until timestamptz;
alter table public.dashboard_users add column if not exists password_changed_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'dashboard_users_role_check'
       and conrelid = 'public.dashboard_users'::regclass
  ) then
    alter table public.dashboard_users
      add constraint dashboard_users_role_check
      check (role in ('admin', 'editor', 'viewer', 'reporter'));
  end if;
end $$;

create table if not exists private.dashboard_sessions (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  employee_no text not null references public.dashboard_users(employee_no) on delete cascade,
  role text not null default 'viewer',
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists private.dashboard_login_events (
  id bigint generated by default as identity primary key,
  employee_no text,
  success boolean not null default false,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists idx_dashboard_sessions_token_hash on private.dashboard_sessions(token_hash);
create index if not exists idx_dashboard_sessions_employee_no on private.dashboard_sessions(employee_no);
create index if not exists idx_dashboard_sessions_expires_at on private.dashboard_sessions(expires_at);
create index if not exists idx_dashboard_login_events_employee_no on private.dashboard_login_events(employee_no, created_at desc);

alter table private.dashboard_sessions enable row level security;
alter table private.dashboard_login_events enable row level security;
revoke all on private.dashboard_sessions from public;
revoke all on private.dashboard_login_events from public;

update public.dashboard_users
   set role = 'admin',
       enabled = true
 where employee_no = '1611499';

create or replace function private.dashboard_token_hash(p_token text)
returns text
language sql
immutable
strict
set search_path = extensions
as $$
  select encode(extensions.digest(p_token, 'sha256'), 'hex');
$$;

create or replace function private.verify_dashboard_login_impl(
  p_employee_no text,
  p_password text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  user_row public.dashboard_users%rowtype;
  raw_token text;
  expires_at timestamptz := now() + interval '12 hours';
  next_failed_count integer;
begin
  select *
    into user_row
    from public.dashboard_users
   where employee_no = trim(p_employee_no)
     and enabled = true;

  if not found then
    insert into private.dashboard_login_events (employee_no, success, reason)
    values (trim(p_employee_no), false, 'not_found');

    return jsonb_build_object('ok', false, 'message', '사번 또는 비밀번호가 일치하지 않습니다.');
  end if;

  if user_row.locked_until is not null and user_row.locked_until > now() then
    insert into private.dashboard_login_events (employee_no, success, reason)
    values (user_row.employee_no, false, 'locked');

    return jsonb_build_object('ok', false, 'message', '로그인 시도가 많아 잠시 잠겼습니다. 잠시 후 다시 시도해 주세요.');
  end if;

  if user_row.password_hash is null
     or extensions.crypt(p_password, user_row.password_hash) <> user_row.password_hash then
    next_failed_count := user_row.failed_login_count + 1;

    update public.dashboard_users
       set failed_login_count = next_failed_count,
           locked_until = case when next_failed_count >= 5 then now() + interval '15 minutes' else null end
     where employee_no = user_row.employee_no;

    insert into private.dashboard_login_events (employee_no, success, reason)
    values (user_row.employee_no, false, case when next_failed_count >= 5 then 'locked_after_failures' else 'bad_password' end);

    return jsonb_build_object('ok', false, 'message', '사번 또는 비밀번호가 일치하지 않습니다.');
  end if;

  raw_token := encode(extensions.gen_random_bytes(32), 'hex');

  insert into private.dashboard_sessions (token_hash, employee_no, role, expires_at, last_seen_at)
  values (private.dashboard_token_hash(raw_token), user_row.employee_no, user_row.role, expires_at, now());

  update public.dashboard_users
     set last_login_at = now(),
         failed_login_count = 0,
         locked_until = null
   where employee_no = user_row.employee_no;

  insert into private.dashboard_login_events (employee_no, success, reason)
  values (user_row.employee_no, true, 'ok');

  return jsonb_build_object(
    'ok', true,
    'employee_no', user_row.employee_no,
    'display_name', coalesce(nullif(user_row.display_name, ''), user_row.employee_no),
    'role', user_row.role,
    'session_token', raw_token,
    'session_expires_at', expires_at
  );
end;
$$;

create or replace function public.verify_dashboard_login(
  p_employee_no text,
  p_password text
)
returns jsonb
language sql
security invoker
set search_path = public, private
as $$
  select private.verify_dashboard_login_impl(p_employee_no, p_password);
$$;

create or replace function public.verify_dashboard_session(
  p_session_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
declare
  session_row private.dashboard_sessions%rowtype;
  user_row public.dashboard_users%rowtype;
begin
  if p_session_token is null or length(trim(p_session_token)) < 32 then
    return jsonb_build_object('ok', false, 'message', 'missing_session');
  end if;

  select *
    into session_row
    from private.dashboard_sessions
   where token_hash = private.dashboard_token_hash(trim(p_session_token))
     and revoked_at is null
     and expires_at > now();

  if not found then
    return jsonb_build_object('ok', false, 'message', 'invalid_session');
  end if;

  select *
    into user_row
    from public.dashboard_users
   where employee_no = session_row.employee_no
     and enabled = true;

  if not found then
    return jsonb_build_object('ok', false, 'message', 'disabled_user');
  end if;

  update private.dashboard_sessions
     set last_seen_at = now()
   where id = session_row.id;

  return jsonb_build_object(
    'ok', true,
    'employee_no', user_row.employee_no,
    'display_name', coalesce(nullif(user_row.display_name, ''), user_row.employee_no),
    'role', user_row.role,
    'session_expires_at', session_row.expires_at
  );
end;
$$;

create or replace function public.revoke_dashboard_session(
  p_session_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private
as $$
begin
  update private.dashboard_sessions
     set revoked_at = now()
   where token_hash = private.dashboard_token_hash(trim(p_session_token))
     and revoked_at is null;

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function private.dashboard_token_hash(text) from public;
revoke all on function private.verify_dashboard_login_impl(text, text) from public;
revoke all on function public.verify_dashboard_login(text, text) from public;
revoke all on function public.verify_dashboard_session(text) from public;
revoke all on function public.revoke_dashboard_session(text) from public;

grant usage on schema private to anon, service_role;
grant execute on function private.verify_dashboard_login_impl(text, text) to anon;
grant execute on function public.verify_dashboard_login(text, text) to anon;
grant execute on function public.verify_dashboard_session(text) to service_role;
grant execute on function public.revoke_dashboard_session(text) to service_role;

revoke all on public.news_articles from anon, authenticated;
revoke all on public.report_runs from anon, authenticated;
revoke all on public.monitor_keywords from anon, authenticated;
revoke all on public.media_relations from anon, authenticated;
revoke all on public.reporters from anon, authenticated;
revoke all on public.ad_spends from anon, authenticated;
revoke all on public.press_aliases from anon, authenticated;

drop policy if exists "public dashboard read news articles" on public.news_articles;
drop policy if exists "public dashboard write news articles" on public.news_articles;
drop policy if exists "public dashboard manage report runs" on public.report_runs;
drop policy if exists "public dashboard manage monitor keywords" on public.monitor_keywords;
drop policy if exists "public dashboard manage media relations" on public.media_relations;
drop policy if exists "public dashboard manage reporters" on public.reporters;
drop policy if exists "public dashboard manage ad spends" on public.ad_spends;
drop policy if exists "public dashboard manage press aliases" on public.press_aliases;
