create table if not exists public.job_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  job_type text not null,
  report_date date,
  report_slot text,
  expected_at timestamptz,
  triggered_by text,
  provider text,
  workflow text,
  github_run_id text,
  github_run_attempt text,
  status text not null default 'started',
  started_at timestamptz,
  finished_at timestamptz,
  last_seen_at timestamptz not null default now(),
  dispatch_count integer not null default 0,
  error text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
      from pg_constraint
     where conname = 'job_runs_job_type_check'
       and conrelid = 'public.job_runs'::regclass
  ) then
    alter table public.job_runs
      add constraint job_runs_job_type_check
      check (job_type in ('daily_report', 'period_report', 'negative_watch', 'watchdog'));
  end if;

  if not exists (
    select 1
      from pg_constraint
     where conname = 'job_runs_status_check'
       and conrelid = 'public.job_runs'::regclass
  ) then
    alter table public.job_runs
      add constraint job_runs_status_check
      check (status in ('started', 'dispatched', 'watchdog_dispatched', 'success', 'failed', 'cancelled', 'skipped'));
  end if;
end $$;

create index if not exists idx_job_runs_expected_at
  on public.job_runs (expected_at desc);
create index if not exists idx_job_runs_type_status
  on public.job_runs (job_type, status, last_seen_at desc);
create index if not exists idx_job_runs_report_slot
  on public.job_runs (report_date desc, report_slot);

drop trigger if exists set_job_runs_updated_at on public.job_runs;
create trigger set_job_runs_updated_at
before update on public.job_runs
for each row execute function public.set_updated_at();

alter table public.job_runs enable row level security;
revoke all on public.job_runs from anon, authenticated;
