create table if not exists public.notification_sends (
  id bigint generated by default as identity primary key,
  sent_at timestamptz not null default now(),
  channel text not null default 'kakao',
  message_type text not null,
  title text,
  body text,
  link_url text,
  status text not null default 'success',
  error text,
  provider_response jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_notification_sends_sent_at
  on public.notification_sends (sent_at desc);

create table if not exists public.negative_watch_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  scanned_at timestamptz not null default now(),
  minutes_back integer not null default 15,
  scanned_count integer not null default 0,
  negative_count integer not null default 0,
  new_negative_count integer not null default 0,
  status text not null default 'scanned',
  message text,
  created_at timestamptz not null default now()
);

create index if not exists idx_negative_watch_runs_scanned_at
  on public.negative_watch_runs (scanned_at desc);

alter table public.notification_sends enable row level security;
alter table public.negative_watch_runs enable row level security;

revoke all on public.notification_sends from anon, authenticated;
revoke all on public.negative_watch_runs from anon, authenticated;
