create table if not exists public.clipping_analysis_reports (
  id bigint generated by default as identity primary key,
  title text not null default '스크랩 기사 분석 보고서',
  prompt text,
  report jsonb not null default '{}'::jsonb,
  analysis text,
  article_count integer not null default 0,
  article_hashes text[] not null default '{}'::text[],
  model text,
  usage jsonb not null default '{}'::jsonb,
  status text not null default 'completed',
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_clipping_analysis_reports_updated_at on public.clipping_analysis_reports;
create trigger set_clipping_analysis_reports_updated_at
before update on public.clipping_analysis_reports
for each row execute function public.set_updated_at();

alter table public.clipping_analysis_reports enable row level security;
revoke all on public.clipping_analysis_reports from anon, authenticated;

create index if not exists idx_clipping_analysis_reports_created_at
on public.clipping_analysis_reports (created_at desc);

create index if not exists idx_clipping_analysis_reports_status
on public.clipping_analysis_reports (status, created_at desc);
