create table if not exists public.risk_response_drafts (
  id bigint generated by default as identity primary key,
  article_hash text not null,
  draft_type text not null check (draft_type in ('press', 'internal')),
  title text not null,
  link text,
  source text,
  tone text default 'negative',
  risk_level text default 'MEDIUM',
  issue text,
  draft text not null,
  status text not null default 'draft',
  model text,
  context jsonb default '{}'::jsonb,
  created_by text default 'negative_watch',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (article_hash, draft_type)
);

create index if not exists idx_risk_response_drafts_created_at
  on public.risk_response_drafts (created_at desc);

create index if not exists idx_risk_response_drafts_status
  on public.risk_response_drafts (status, created_at desc);

drop trigger if exists set_risk_response_drafts_updated_at on public.risk_response_drafts;
create trigger set_risk_response_drafts_updated_at
before update on public.risk_response_drafts
for each row execute function public.set_updated_at();

alter table public.risk_response_drafts enable row level security;

revoke all on public.risk_response_drafts from anon, authenticated;
